ecs_cluster_name     = "wtc-ecs-cluster-prod"
ecs_service_name     = "wtc-ecs-service-prod"
ecs_task_defn_family = "wtc-ecs-task-def-prod"
ecs_container_name   = "wtc-container-prod"
ecs_port_name        = "wtc-3000-tcp-prod"